const policyData = [
  {
    title: "Croatia Summit Position Paper",
    group: "Model EU & Model UN",
    forum: "Model EU",
    context: "Summit position paper",
    date: null,
    about: "Lays out Croatia's position across five EU policy areas: the financial market, defense, agriculture, the environment, and the 2021–2027 EU budget.",
    highlights: [
      "Defense: argues PESCO projects should require EU approval so member states can't design projects that threaten allies or cost too much.",
      "Agriculture: supports keeping the CAP at 30% of the budget, as long as it shifts toward environmental goals and small and medium-sized farms.",
      "Environment: backs the 8th Environment Action Programme but says circular economy and biodiversity (about 10% each) deserve more funding.",
      "Budget: proposes 30% for Single Market, Innovation and Digital and 25% for Migration and Border Management.",
    ],
    tags: ["Financial Markets", "Defense", "CAP", "Environment", "EU Budget"],
    paperLink: "/papers/Croatia_Summit_Paper.pdf",
  },
  {
    title: "Croatia Agriculture",
    group: "Model EU & Model UN",
    forum: "Model EU",
    context: "Policy memo · JSIS B 431",
    date: "Nov 15, 2021",
    about: "Examines how fragmented landownership, small farms, and weak agribusiness competitiveness hold back Croatia's agricultural sector and weighs three policy options.",
    highlights: [
      "Problem: about 64% of registered farms are under 5 hectares, and an outdated land registry slows land transfers.",
      "Options: €10 billion in CAP funding, stronger anti-corruption measures, or an agriculture-focused free trade agreement.",
      "Recommendation: a free trade agreement with select EU members to cut subsidies and trade restrictions and attract foreign investment.",
    ],
    tags: ["Agriculture", "Rural Development", "Free Trade", "Land Administration"],
    paperLink: "/papers/MODEL_EU_CroatiaAgriculture.pdf",
  },
  {
    title: "Croatia Immigration/Emigration",
    group: "Model EU & Model UN",
    forum: "Model EU",
    context: "Policy memo · JSIS B 431",
    date: "Nov 7, 2021",
    about: "Addresses two pressures on Croatia at once: handling migrants and asylum-seekers at its border, and an emigration rate among the highest in the EU.",
    highlights: [
      "Border: an independent human rights monitoring mechanism and a larger, more efficient asylum system.",
      "Emigration: ties people leaving to socioeconomic factors, citing a survey where 65% pointed to poor development and 53% to corruption.",
      "Recommendation: ask the EU's AMIF to double Croatia's funding (about €108M to €216M) and raise its ESF+ funding from €110M to €200M.",
    ],
    tags: ["Migration", "Asylum Policy", "Border Management", "EU Funding"],
    paperLink: "/papers/MODEL_EU_CroatiaImmigration.pdf",
  },
  {
    title: "Croatia Defense Policy",
    group: "Model EU & Model UN",
    forum: "Model EU",
    context: "Policy memo · JSIS B 431",
    date: "Oct 25, 2021",
    about: "Looks at how Croatia can modernize its outdated armed and air forces despite tight budgets, shrinking personnel, and NATO expectations.",
    highlights: [
      "Context: personnel fell from 22,000 in 2008 to about 18,525 in 2018, and Croatia aims to reach NATO's 2% of GDP target by 2024.",
      "Options: source equipment from more EU and NATO members, sign a defense-industry agreement, or press the EU defense fund to double Croatia's forces.",
      "Recommendation: a defense-industry agreement with other NATO members to share technology and tap the European Defence Fund.",
    ],
    tags: ["Defense", "NATO", "Military Modernization", "European Defence Fund"],
    paperLink: "/papers/MODEL_EU_CroatiaDefense.pdf",
  },
  {
    title: "Burkina Faso at the UN Commission on Crime Prevention and Criminal Justice",
    group: "Model EU & Model UN",
    forum: "Model UN",
    context: "Position paper · University of Washington delegation",
    date: "2019",
    about: "Burkina Faso's position on advancing crime prevention and the rule of law toward the 2030 Agenda, and on strengthening responses to violence against women.",
    highlights: [
      "Crime and the rule of law: links crime to poverty, urbanization, and trafficking, and focuses on money laundering and terrorism in the Sahel.",
      "Recommendation: UNODC and UNOCT should coordinate with each other, and with UNCAC on money laundering, to strengthen Burkina Faso's criminal justice system and counter terrorism.",
      "Violence against women: cites a 183rd of 189 ranking on the 2018 Human Development Report and urges UNFPA, OHCHR, and UNODC to work together.",
    ],
    tags: ["Crime Prevention", "Criminal Justice", "Counter-Terrorism", "Violence Against Women"],
    paperLink: "/papers/ModelUN_BurkinaFaso_2019.pdf",
  },
  {
    title: "Reforming the Electoral College",
    group: "Policy Memos, Papers & Testimony",
    forum: "Testimony",
    context: "House Oversight and Reform Committee",
    date: "Jun 6, 2021",
    about: "Argues for keeping the Electoral College but ending winner-take-all by splitting each state's electoral votes according to the popular vote.",
    highlights: [
      "Problem: winner-take-all gives swing states too much power and leaves voters in partisan states feeling ignored, which the testimony argues can depress turnout.",
      "Proposal: keep the Electoral College but give each candidate electoral votes in proportion to their share of a state's popular vote, rounded to whole numbers.",
      "Example: in 2016, winner-take-all gave Trump 20 electoral votes to Clinton's 13 across Massachusetts, Arizona, and Wisconsin, even though Clinton led their combined popular vote.",
      "Result: under the proposed method, the same three states would give Clinton 18 electoral votes to Trump's 14.",
    ],
    tags: ["Electoral College", "Election Reform", "Proportional Allocation", "Voter Turnout"],
    paperLink: "/papers/Reforming_Electoral_College.pdf",
  },
  {
    title: "U.S. Trade Policy",
    group: "Policy Memos, Papers & Testimony",
    forum: "Policy Memo",
    context: "Memo to Joe Biden · POL S 203",
    date: "May 17, 2020",
    about: "Argues the U.S. should stay committed to free trade rather than shift to protectionism, and proposes trade deals to boost U.S. exports.",
    highlights: [
      "Context: weighs free trade's benefits, such as growth and lower consumer prices, against outsourcing, citing a 2011 Economic Policy Institute estimate of 682,900 jobs lost since NAFTA.",
      "Problem: argues the Trump administration's tariffs triggered a trade war with China, citing the Tax Foundation for an $80 billion tax increase on Americans and a projected 394,000 jobs lost.",
      "China proposal: a deal making U.S. exports to China equal U.S. imports from China, so there is no deficit, by boosting agricultural, natural resource, industrial supply, and capital goods exports.",
      "Wider proposal: a trade agreement with perhaps five to ten other countries, excluding China, to export goods like clothes, computers, and telephones and bring total exports above imports.",
    ],
    tags: ["Trade Policy", "Free Trade", "Tariffs", "Trade Deficit", "U.S.–China Trade"],
    paperLink: "/papers/Trade_Policy_Memo.pdf",
  },
  {
    title: "Reforming the International Criminal Court",
    group: "Policy Memos, Papers & Testimony",
    forum: "Policy Paper",
    context: "POL S 328: International Organizations",
    date: "Mar 14, 2020",
    about: "Examines criticisms of the International Criminal Court's speed, cost, and ties to the UN Security Council, and argues for limiting the Council's role and managing public expectations.",
    highlights: [
      "Criticism: lengthy, complicated proceedings and the UN Security Council's ability to defer hearings for 6 or 12 months make the Court seem ineffective.",
      "Cost: about €1.5 billion spent for only three convictions of core international crimes, with the Bemba and Gbagbo acquittals raising doubts about high-level prosecutions.",
      "Recommendation: pressure Russia, America, and China to ratify the Rome Statute, and limit the UN Security Council's role in ICC proceedings until all its members ratify.",
      "Recommendation: educate the international community that the ICC can prosecute only acts after 2002, with ICC outreach to local governments and civil society to manage expectations.",
    ],
    tags: ["International Criminal Court", "Rome Statute", "International Law", "UN Security Council"],
    paperLink: "/papers/Reforming_ICC.pdf",
  },
  {
    title: "Reforming UN Security Council Voting",
    group: "Policy Memos, Papers & Testimony",
    forum: "Policy Memo",
    context: "Memo to the UNSC President · POL S 328",
    date: "Jan 31, 2020",
    about: "Argues that the P5 veto leaves non-permanent UN Security Council members as observers and proposes a US-style voting system in which a two-thirds majority can override a veto.",
    highlights: [
      "Problem: the paper argues the P5 (Britain, France, United States, Russia, China) can block any action a majority of members wants, while the ten non-permanent members have no veto.",
      "Examples: the paper asserts the veto shielded the US (its Israel moves), Russia (Crimea annexation), and China (Uighur camps) from resolutions a majority of members supported.",
      "Proposal: voting modeled on the US government, with the P5 holding the veto like the President and a two-thirds majority (ten members) able to override it like Congress.",
      "Risk: the paper warns the override might lead some P5 members, especially the US, to consider leaving or make a UN collapse more likely, since it argues they stay for the veto's foreign policy value.",
    ],
    tags: ["UN Security Council", "Veto Power", "Institutional Reform", "International Organizations"],
    paperLink: "/papers/Reforming_UNSC.pdf",
  },
];

export default policyData;
